import { AdhkarItem, DhikrPreset } from "../types";

export const DEFAULT_DHIKR_PRESETS: DhikrPreset[] = [
  {
    id: "subhanallah",
    title: "SubhanAllah",
    arabic: "سُبْحَانَ اللَّهِ",
    transliteration: "Subḥānallāh",
    translation: "Glory be to Allah",
    virtue: "Whoever says SubhanAllah 100 times, 1,000 good deeds are recorded or 1,000 sins are removed (Sahih Muslim).",
    targetCount: 33,
  },
  {
    id: "alhamdulillah",
    title: "Alhamdulillah",
    arabic: "الْحَمْدُ لِلَّهِ",
    transliteration: "Al-ḥamdulillāh",
    translation: "Praise be to Allah",
    virtue: "Alhamdulillah fills the scale of good deeds (Sahih Muslim).",
    targetCount: 33,
  },
  {
    id: "allahuakbar",
    title: "Allahu Akbar",
    arabic: "اللَّهُ أَكْبَرُ",
    transliteration: "Allāhu Akbar",
    translation: "Allah is the Greatest",
    virtue: "Among the four most beloved phrases to Allah.",
    targetCount: 34,
  },
  {
    id: "astaghfirullah",
    title: "Astaghfirullah",
    arabic: "أَسْتَغْفِرُ اللَّهَ",
    transliteration: "Astaghfirullāh",
    translation: "I seek forgiveness from Allah",
    virtue: "The Prophet (ﷺ) said: 'I seek Allah's forgiveness more than 70 times a day' (Bukhari).",
    targetCount: 100,
  },
  {
    id: "tahlil",
    title: "La ilaha illallah",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ",
    transliteration: "Lā ilāha illallāh",
    translation: "There is no deity worthy of worship except Allah",
    virtue: "The best dhikr is 'La ilaha illallah' (Tirmidhi).",
    targetCount: 100,
  },
  {
    id: "salawat",
    title: "Salawat 'ala an-Nabi",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
    transliteration: "Allāhumma ṣalli 'alā Muḥammadin wa 'alā āli Muḥammad",
    translation: "O Allah, send blessings upon Muhammad and upon the family of Muhammad",
    virtue: "Whoever sends blessings upon me once, Allah sends blessings upon him ten times (Muslim).",
    targetCount: 100,
  },
  {
    id: "hawqala",
    title: "La hawla wa la quwwata",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Lā ḥawla wa lā quwwata illā billāh",
    translation: "There is no power nor strength except through Allah",
    virtue: "It is a treasure from the treasures of Paradise (Sahih Bukhari).",
    targetCount: 33,
  },
  {
    id: "subhanallahi-wabihamdihi",
    title: "Subhanallahi wa bihamdihi",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
    transliteration: "Subḥānallāhi wa bi-ḥamdihi, Subḥānallāhil-'Aẓīm",
    translation: "Glory be to Allah and His praise, Glory be to Allah the Magnificent",
    virtue: "Two words that are beloved to the Most Merciful, light on the tongue, heavy on the balance (Bukhari & Muslim).",
    targetCount: 100,
  },
];

export const ADHKAR_LIST: AdhkarItem[] = [
  // Morning Adhkar
  {
    id: "m-1",
    category: "morning",
    title: "Ayat al-Kursi (The Throne Verse)",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    transliteration: "Allāhu lā ilāha illā Huwal-Ḥayyul-Qayyūm, lā ta'khudhuhū sinatun walā nawm, lahū mā fis-samāwāti wamā fil-arḍ...",
    translation: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep...",
    reference: "Whoever recites this when he awakens will be protected from jinn until evening (Al-Hakim, Sahih).",
    targetCount: 1,
  },
  {
    id: "m-2",
    category: "morning",
    title: "Sayyid al-Istighfar (The Master Supplication for Forgiveness)",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ ، خَلَقْتَنِي وَأَنَا عَبْدُكَ ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    transliteration: "Allāhumma Anta Rabbī lā ilāha illā Anta, khalaqtanī wa anā 'abduka, wa anā 'alā 'ahdika wa wa'dika mastata'tu, a'ūdhu bika min sharri mā ṣana'tu, abū'u laka bini'matika 'alayya, wa abū'u laka bidhanbī faghfir lī fa-innahū lā yaghfirudh-dhunūba illā Anta",
    translation: "O Allah, You are my Lord, none has the right to be worshipped but You. You created me and I am Your servant...",
    reference: "Whoever says this with certainty during the morning and dies before evening will enter Paradise (Bukhari).",
    targetCount: 1,
  },
  {
    id: "m-3",
    category: "morning",
    title: "Supplication for Protection from Harm",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration: "Bismillāhilladhī lā yaḍurru ma'as-mihī shay'un fil-arḍi walā fis-samā'i wa Huwas-Samī'ul-'Alīm",
    translation: "In the name of Allah, with whose name nothing can cause harm in the earth or in the heavens, and He is the All-Hearing, the All-Knowing.",
    reference: "Whoever says it three times in the morning and three times in the evening, nothing will harm him (Abu Dawood & Tirmidhi).",
    targetCount: 3,
  },
  {
    id: "m-4",
    category: "morning",
    title: "Pleased with Allah as my Lord",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا ، وَبِالْإِسْلَامِ دِينًا ، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا",
    transliteration: "Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin (ṣallāllāhu 'alayhi wa sallam) Nabiyyā",
    translation: "I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (ﷺ) as my Prophet.",
    reference: "Whoever says this in the morning and evening, Allah takes it upon Himself to satisfy him on the Day of Resurrection (Tirmidhi).",
    targetCount: 3,
  },

  // Evening Adhkar
  {
    id: "e-1",
    category: "evening",
    title: "Evening Declaration of Kingdom",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ ، وَالْحَمْدُ لِلَّهِ ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "Amsaynā wa amsal-mulku lillāh, wal-ḥamdu lillāh, lā ilāha illallāhu waḥdahū lā sharīka lah, lahul-mulku wa lahul-ḥamdu wa Huwa 'alā kulli shay'in Qadīr",
    translation: "We have reached the evening and with it all dominion belongs to Allah. Praise be to Allah. None has the right to be worshipped except Allah alone, without partner...",
    reference: "Recited by the Prophet (ﷺ) in the evening (Sahih Muslim).",
    targetCount: 1,
  },
  {
    id: "e-2",
    category: "evening",
    title: "Seeking Refuge in the Perfect Words of Allah",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'ūdhu bi-kalimātillāhit-tāmmāti min sharri mā khalaq",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    reference: "Whoever recites this thrice in the evening will not be harmed by any sting/creature that night (Muslim).",
    targetCount: 3,
  },

  // Post-Prayer Adhkar
  {
    id: "p-1",
    category: "prayer",
    title: "Istighfar after Salam",
    arabic: "أَسْتَغْفِرُ اللَّهَ ، أَسْتَغْفِرُ اللَّهَ ، أَسْتَغْفِرُ اللَّهَ ، اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالإِكْرَامِ",
    transliteration: "Astaghfirullāh (3x), Allāhumma Antas-Salāmu wa minkas-salām, tabārakta yā Dhal-Jalāli wal-Ikrām",
    translation: "I ask Allah for forgiveness (3x). O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of Majesty and Honor.",
    reference: "Sunnah immediately after every Fardh prayer (Muslim).",
    targetCount: 1,
  },
  {
    id: "p-2",
    category: "prayer",
    title: "Tasbih, Tahmid, and Takbir",
    arabic: "سُبْحَانَ اللَّهِ (٣٣) ، الْحَمْدُ لِلَّهِ (٣٣) ، اللَّهُ أَكْبَرُ (٣٣) ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ (١)",
    transliteration: "Subḥānallāh (33x), Al-ḥamdulillāh (33x), Allāhu Akbar (33x) + Lā ilāha illallāhu waḥdahū lā sharīka lah (1x)",
    translation: "Glory be to Allah (33x), Praise be to Allah (33x), Allah is greatest (33x), followed by the declaration of Tawheed.",
    reference: "Whoever says this after every prayer will have his sins forgiven even if they were like the foam of the sea (Muslim).",
    targetCount: 33,
  },

  // Sleeping Duas
  {
    id: "s-1",
    category: "sleeping",
    title: "Dua Before Sleeping",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismikallāhumma amūtu wa aḥyā",
    translation: "In Your name, O Allah, I die and I live.",
    reference: "Recited when lying down to sleep (Sahih Bukhari).",
    targetCount: 1,
  },
  {
    id: "s-2",
    category: "sleeping",
    title: "The Mu'awwidhatayn & Surah Al-Ikhlas",
    arabic: "قراءة سورة الإخلاص، والفلق، والناس مع النفث في الكفين ومسح الجسد",
    transliteration: "Reciting Surah Al-Ikhlas, Al-Falaq, and An-Nas into palms and wiping over body",
    translation: "Recite the three Quls, blow gently into hands, and wipe as much of the body as possible, starting with head and face (repeat 3 times).",
    reference: "Habit of the Prophet (ﷺ) every night before sleeping (Bukhari).",
    targetCount: 3,
  },
];
