import { QamusEntry, QamusGrammarRule, QamusRootInfo } from "../types/qamus.types";

export const CURATED_ROOTS: QamusRootInfo[] = [
  {
    root: "ك-ت-ب",
    rootArabic: "كتب",
    transliteration: "k-t-b",
    generalMeaning: "To write, record, prescribe, decree, bind",
    occurrencesInQuran: 319,
  },
  {
    root: "ر-ح-م",
    rootArabic: "رحم",
    transliteration: "r-ḥ-m",
    generalMeaning: "To have mercy, compassion, tenderness, womb",
    occurrencesInQuran: 563,
  },
  {
    root: "ع-ل-م",
    rootArabic: "علم",
    transliteration: "‘-l-m",
    generalMeaning: "To know, understand, perceive, mark, teach",
    occurrencesInQuran: 854,
  },
  {
    root: "س-ل-م",
    rootArabic: "سلم",
    transliteration: "s-l-m",
    generalMeaning: "To be safe, whole, sound, submit, greet with peace",
    occurrencesInQuran: 140,
  },
  {
    root: "ص-ب-ر",
    rootArabic: "صبر",
    transliteration: "ṣ-b-r",
    generalMeaning: "Patience, endurance, steadfast restraint, perseverance",
    occurrencesInQuran: 103,
  },
  {
    root: "ح-م-د",
    rootArabic: "حمد",
    transliteration: "ḥ-m-d",
    generalMeaning: "Praise, gratitude, laudation, appreciation",
    occurrencesInQuran: 68,
  },
  {
    root: "ن-و-ر",
    rootArabic: "نور",
    transliteration: "n-w-r",
    generalMeaning: "Light, illumination, clarity, divine guidance",
    occurrencesInQuran: 194,
  },
  {
    root: "ع-ب-د",
    rootArabic: "عبد",
    transliteration: "‘-b-d",
    generalMeaning: "To serve, worship, yield, submit as a servant",
    occurrencesInQuran: 275,
  },
  {
    root: "ه-د-ي",
    rootArabic: "هدي",
    transliteration: "h-d-y",
    generalMeaning: "To guide, show the way, offer a gift, lead",
    occurrencesInQuran: 316,
  },
  {
    root: "ش-ك-ر",
    rootArabic: "شكر",
    transliteration: "sh-k-r",
    generalMeaning: "To thank, appreciate, acknowledge goodness",
    occurrencesInQuran: 75,
  },
];

export const CURATED_ENTRIES: Record<string, QamusEntry> = {
  كتب: {
    query: "كتب",
    normalizedQuery: "كتب",
    wordType: "verb",
    tashkeel: "كَتَبَ",
    transliteration: "kataba",
    phoneticSpelling: "ka-ta-ba",
    rootInfo: {
      root: "ك-ت-ب",
      rootArabic: "كتب",
      transliteration: "k-t-b",
      generalMeaning: "writing, prescribing, decreeing",
      occurrencesInQuran: 319,
    },
    meanings: {
      primaryEnglish: "To write, inscribe, prescribe, or ordain",
      primaryAmharic: "ጻፈ፣ ደነገገ፣ ቆጠረ",
      secondaryEnglish: [
        "To author a work",
        "To decree or make obligatory (in religious jurisprudence)",
        "To contract or register",
      ],
      classicalArabicDefinition:
        "الكَتْبُ: ضَمُّ أَدِيمٍ إِلى أَدِيمٍ بِالخِياطَةِ، وفي الشَّرِيعَةِ: الفَرْضُ والإِيجابُ كَقَوْلِهِ تَعَالَى كُتِبَ عَلَيْكُمُ الصِّيَامُ",
      hansWehrEquivalent: "kataba u (katb, kitāba) to write, set down in writing, record; to prescribe, decree",
    },
    grammar: {
      partOfSpeechArabic: "فعل ماض",
      partOfSpeechEnglish: "Past tense triliteral verb (Form I)",
      patterns: "فَعَلَ (Fa'ala)",
      irabAnalysis: [
        {
          word: "كَتَبَ",
          transliteration: "kataba",
          partOfSpeech: "فعل",
          role: "فعل ماض مبني على الفتح الظاهر على آخره",
          caseOrState: "مبني على الفتح (Indeclinable upon fatha)",
          explanationEnglish: "Triliteral root verb in the perfect past aspect, third person masculine singular.",
        },
      ],
      morphologicalForms: [
        {
          formNumber: "Form I (فَعَلَ)",
          past: "كَتَبَ",
          present: "يَكْتُبُ",
          verbalNoun: "كِتَابَةٌ / كَتْبٌ",
          activeParticiple: "كَاتِبٌ (Writer)",
          passiveParticiple: "مَكْتُوبٌ (Written/Destined)",
          meaning: "To write, prescribe",
        },
        {
          formNumber: "Form II (فَعَّلَ)",
          past: "كَتَّبَ",
          present: "يُكَتِّبُ",
          verbalNoun: "تَكْتِيبٌ",
          activeParticiple: "مُكَتِّبٌ",
          passiveParticiple: "مُكَتَّبٌ",
          meaning: "To teach to write, make write",
        },
        {
          formNumber: "Form III (فَاعَلَ)",
          past: "كَاتَبَ",
          present: "يُكَاتِبُ",
          verbalNoun: "مُكَاتَبَةٌ",
          activeParticiple: "مُكَاتِبٌ",
          passiveParticiple: "مُكَاتَبٌ",
          meaning: "To correspond with, exchange letters",
        },
        {
          formNumber: "Form IV (أَفْعَلَ)",
          past: "أَكْتَبَ",
          present: "يُكْتِبُ",
          verbalNoun: "إِكْتَابٌ",
          activeParticiple: "مُكْتِبٌ",
          meaning: "To dictate, cause to write",
        },
        {
          formNumber: "Form VIII (اِفْتَعَلَ)",
          past: "اِكْتَتَبَ",
          present: "يَكْتَتِبُ",
          verbalNoun: "اِكْتِتَابٌ",
          activeParticiple: "مُكْتَتِبٌ",
          passiveParticiple: "مُكْتَتَبٌ",
          meaning: "To subscribe, copy down, get oneself registered",
        },
        {
          formNumber: "Form X (اِسْتَفْعَلَ)",
          past: "اِسْتَكْتَبَ",
          present: "يَسْتَكْتِبُ",
          verbalNoun: "اِسْتِكْتَابٌ",
          activeParticiple: "مُسْتَكْتِبٌ",
          meaning: "To ask someone to write",
        },
      ],
    },
    synonyms: [
      { arabic: "دَوَّنَ", english: "To record, log" },
      { arabic: "سَطَّرَ", english: "To line, inscribe" },
      { arabic: "فَرَضَ", english: "To decree, obligate" },
    ],
    antonyms: [
      { arabic: "مَحَا", english: "To erase, efface" },
      { arabic: "طَمَسَ", english: "To obliterate" },
    ],
    examples: [
      {
        arabic: "كَتَبَ الطَّالِبُ الدَّرْسَ بِعِنَايَةٍ.",
        english: "The student wrote the lesson with great care.",
        amharic: "ተማሪው ትምህርቱን በጥንቃቄ ጻፈ።",
      },
      {
        arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الصِّيَامُ",
        english: "O you who have believed, decreed upon you is fasting. [Al-Baqarah 2:183]",
        amharic: "እናንተ ያመናችሁ ሆይ! ጾም በናንተ ላይ ተደነገገ።",
      },
    ],
    quranicInsights: {
      totalOccurrences: 319,
      surahsWithHighFrequency: ["Al-Baqarah", "An-Nisa", "Al-A'raf", "At-Tawbah"],
      spiritualLesson:
        "The root relates both to earthly recording of deeds by the noble scribes (Kiram Katibin) and Allah's eternal decree (Al-Lawh Al-Mahfuz).",
      keyVerses: [
        {
          surahNumber: 2,
          ayahNumber: 183,
          surahNameArabic: "البقرة",
          surahNameEnglish: "Al-Baqarah",
          ayahArabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الصِّيَامُ كَمَا كُتِبَ عَلَى الَّذِينَ مِن قَبْلِكُمْ",
          ayahTranslation: "O you who have believed, decreed upon you is fasting as it was decreed upon those before you.",
          highlightedWord: "كُتِبَ",
        },
        {
          surahNumber: 6,
          ayahNumber: 12,
          surahNameArabic: "الأنعام",
          surahNameEnglish: "Al-An'am",
          ayahArabic: "كَتَبَ عَلَىٰ نَفْسِهِ الرَّحْمَةَ",
          ayahTranslation: "He has prescribed mercy upon Himself.",
          highlightedWord: "كَتَبَ",
        },
      ],
    },
    source: "lexicon-db",
    timestamp: Date.now(),
  },
  رحمة: {
    query: "رحمة",
    normalizedQuery: "رحمة",
    wordType: "noun",
    tashkeel: "رَحْمَةٌ",
    transliteration: "raḥmah",
    phoneticSpelling: "rah-mah",
    rootInfo: {
      root: "ر-ح-م",
      rootArabic: "رحم",
      transliteration: "r-ḥ-m",
      generalMeaning: "mercy, compassion, maternal affection",
      occurrencesInQuran: 563,
    },
    meanings: {
      primaryEnglish: "Mercy, divine grace, compassion, tenderness",
      primaryAmharic: "እዝነት፣ ምህረት፣ ቸርነት",
      secondaryEnglish: ["Beneficence", "Pity, benevolence", "Spiritual blessing, rain (as divine mercy)"],
      classicalArabicDefinition: "الرَّحْمَةُ: الرِّقَّةُ والتَّعَطُّفُ والمَغْفِرَةُ، وَأَصْلُهَا مِنَ الرَّحِمِ لِاشْتِقاقِهَا مِنْهَا لِصِلَةِ القَرَابَةِ",
      hansWehrEquivalent: "raḥma mercy, compassion, clemency, kindness, benevolence",
    },
    grammar: {
      partOfSpeechArabic: "اسم مؤنث (مصدر)",
      partOfSpeechEnglish: "Feminine verbal noun (Masdar)",
      grammaticalGender: "feminine",
      number: "singular",
      pluralForm: "رَحَمَاتٌ (Raḥamāt)",
      patterns: "فَعْلَةٌ (Fa'lah)",
      irabAnalysis: [
        {
          word: "رَحْمَةٌ",
          transliteration: "raḥmah",
          partOfSpeech: "اسم",
          role: "اسم مفرد مؤنث بالتاء المربوطة",
          caseOrState: "حسب موقعه في الجملة (مرفوع بالضمة / منصوب بالفتحة / مجرور بالكسرة)",
          explanationEnglish: "Singular noun marked feminine by Ta Marbuta (ة).",
        },
      ],
      morphologicalForms: [
        {
          formNumber: "Form I (فَعِلَ)",
          past: "رَحِمَ",
          present: "يَرْحَمُ",
          verbalNoun: "رَحْمَةٌ / رُحْمٌ",
          activeParticiple: "رَاحِمٌ (Merciful)",
          passiveParticiple: "مَرْحُومٌ (Recipient of mercy)",
          meaning: "To show mercy, pity",
        },
        {
          formNumber: "Intensive Adjective (فَعِيل)",
          past: "—",
          present: "—",
          verbalNoun: "—",
          activeParticiple: "رَحِيمٌ (Especially Merciful)",
          meaning: "Expresses intensive and continuous mercy (Divine Name)",
        },
        {
          formNumber: "Vastness Adjective (فَعْلَان)",
          past: "—",
          present: "—",
          verbalNoun: "—",
          activeParticiple: "رَحْمَٰنٌ (Entirely Merciful)",
          meaning: "Universal, encompassing mercy for all creation (Divine Name)",
        },
      ],
    },
    synonyms: [
      { arabic: "شَفَقَةٌ", english: "Compassion, tenderness" },
      { arabic: "رَأْفَةٌ", english: "Kindness, clemency" },
      { arabic: "مَغْفِرَةٌ", english: "Pardon, forgiveness" },
    ],
    antonyms: [
      { arabic: "قَسْوَةٌ", english: "Harshness, cruelty" },
      { arabic: "غِلْظَةٌ", english: "Roughness, severity" },
    ],
    examples: [
      {
        arabic: "ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ.",
        english: "Have mercy on those on the earth, and the One in heaven will have mercy on you. [Tirmidhi]",
        amharic: "በምድር ላሉት እዘኑ፤ በሰማይ ያለው ይምራችኋልና።",
      },
      {
        arabic: "وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ",
        english: "And My mercy encompasses all things. [Al-A'raf 7:156]",
        amharic: "እዝነቴም ሁሉንም ነገር አካብባለች።",
      },
    ],
    quranicInsights: {
      totalOccurrences: 563,
      surahsWithHighFrequency: ["Al-Fatihah", "Maryam", "Al-Anbiya", "Al-A'raf"],
      spiritualLesson:
        "Mercy is the pre-eminent divine attribute; every Surah except Surah At-Tawbah commences with the divine names Ar-Rahman and Ar-Rahim.",
      keyVerses: [
        {
          surahNumber: 21,
          ayahNumber: 107,
          surahNameArabic: "الأنبياء",
          surahNameEnglish: "Al-Anbiya",
          ayahArabic: "وَمَا أَرْسَلْنَاكَ إِلَّا رَحْمَةً لِّلْعَالَمِينَ",
          ayahTranslation: "And We have not sent you, [O Muhammad], except as a mercy to the worlds.",
          highlightedWord: "رَحْمَةً",
        },
      ],
    },
    source: "lexicon-db",
    timestamp: Date.now(),
  },
  علم: {
    query: "علم",
    normalizedQuery: "علم",
    wordType: "noun",
    tashkeel: "عِلْمٌ",
    transliteration: "‘ilm",
    phoneticSpelling: "ilm",
    rootInfo: {
      root: "ع-ل-م",
      rootArabic: "علم",
      transliteration: "‘-l-m",
      generalMeaning: "knowledge, discernment, perception, teaching",
      occurrencesInQuran: 854,
    },
    meanings: {
      primaryEnglish: "Knowledge, science, learning, discernment",
      primaryAmharic: "ዕውቀት፣ ትምህርት፣ ማወቅ",
      secondaryEnglish: ["Intellectual discipline", "Divine gnosis", "Certainty and proof"],
      classicalArabicDefinition: "العِلْمُ: إِدْراكُ الشَّيْءِ بِحَقِيقَتِهِ، وَهُوَ ضِدُّ الجَهْلِ، وَعَلِمَ الشَّيْءَ عِلْماً: عَرَفَهُ وَتَيَقَّنَهُ",
      hansWehrEquivalent: "‘ilm knowledge, learning, lore, science, scholarship",
    },
    grammar: {
      partOfSpeechArabic: "اسم مفرد (مصدر)",
      partOfSpeechEnglish: "Singular masculine verbal noun",
      grammaticalGender: "masculine",
      number: "singular",
      pluralForm: "عُلُومٌ (‘Ulūm)",
      patterns: "فِعْلٌ (Fi'l)",
      irabAnalysis: [
        {
          word: "عِلْمٌ",
          transliteration: "‘ilm",
          partOfSpeech: "اسم",
          role: "اسم مفرد مذكر",
          caseOrState: "معرب (Declinable according to syntactic position)",
          explanationEnglish: "Base noun, can appear with Tanween or Idhafah.",
        },
      ],
      morphologicalForms: [
        {
          formNumber: "Form I (فَعِلَ)",
          past: "عَلِمَ",
          present: "يَعْلَمُ",
          verbalNoun: "عِلْمٌ",
          activeParticiple: "عَالِمٌ (Scholar, Knower)",
          passiveParticiple: "مَعْلُومٌ (Known, specified)",
          meaning: "To know, ascertain",
        },
        {
          formNumber: "Form II (فَعَّلَ)",
          past: "عَلَّمَ",
          present: "يُعَلِّمُ",
          verbalNoun: "تَعْلِيمٌ",
          activeParticiple: "مُعَلِّمٌ (Teacher)",
          passiveParticiple: "مُعَلَّمٌ",
          meaning: "To instruct, impart knowledge",
        },
        {
          formNumber: "Form V (تَفَعَّلَ)",
          past: "تَعَلَّمَ",
          present: "يَتَعَلَّمُ",
          verbalNoun: "تَعَلُّمٌ",
          activeParticiple: "مُتَعَلِّمٌ (Student, learner)",
          meaning: "To learn, study",
        },
      ],
    },
    synonyms: [
      { arabic: "مَعْرِفَةٌ", english: "Recognition, acquaintance" },
      { arabic: "دِرَايَةٌ", english: "Insight, awareness" },
      { arabic: "حِكْمَةٌ", english: "Wisdom" },
    ],
    antonyms: [
      { arabic: "جَهْلٌ", english: "Ignorance" },
      { arabic: "غَفْلَةٌ", english: "Heedlessness, unawareness" },
    ],
    examples: [
      {
        arabic: "طَلَبُ العِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ.",
        english: "Seeking knowledge is an obligation upon every Muslim. [Ibn Majah]",
        amharic: "ዕውቀትን መፈለግ በእያንዳንዱ ሙስሊም ላይ ግዴታ ነው።",
      },
      {
        arabic: "وَقُل رَّبِّ زِدْنِي عِلْمًا",
        english: "And say: 'My Lord, increase me in knowledge.' [Ta-Ha 20:114]",
        amharic: "«ጌታዬ ሆይ! ዕውቀትን ጨምርልኝ» በል።",
      },
    ],
    quranicInsights: {
      totalOccurrences: 854,
      surahsWithHighFrequency: ["Al-Baqarah", "Ali 'Imran", "Al-Kahf", "Al-Alaq"],
      spiritualLesson:
        "The very first revelation to the Prophet (pbuh) was 'Iqra' (Read) emphasizing education, pen, and intellect.",
      keyVerses: [
        {
          surahNumber: 20,
          ayahNumber: 114,
          surahNameArabic: "طه",
          surahNameEnglish: "Ta-Ha",
          ayahArabic: "فَتَعَالَى اللَّهُ الْمَلِكُ الْحَقُّ ۗ وَلَا تَعْجَلْ بِالْقُرْآنِ مِن قَبْلِ أَن يُقْضَىٰ إِلَيْكَ وَحْيُهُ ۖ وَقُل رَّبِّ زِدْنِي عِلْمًا",
          ayahTranslation: "So high [above all] is Allah, the Sovereign, the Truth. And do not hasten with the Qur'an before its revelation is completed to you, and say, 'My Lord, increase me in knowledge.'",
          highlightedWord: "عِلْمًا",
        },
      ],
    },
    source: "lexicon-db",
    timestamp: Date.now(),
  },
  صبر: {
    query: "صبر",
    normalizedQuery: "صبر",
    wordType: "noun",
    tashkeel: "صَبْرٌ",
    transliteration: "ṣabr",
    phoneticSpelling: "sabr",
    rootInfo: {
      root: "ص-ب-ر",
      rootArabic: "صبر",
      transliteration: "ṣ-b-r",
      generalMeaning: "steadfastness, patience, self-restraint",
      occurrencesInQuran: 103,
    },
    meanings: {
      primaryEnglish: "Patience, perseverance, steadfastness, endurance",
      primaryAmharic: "ትዕግስት፣ ጽናት፣ መቋቋም",
      secondaryEnglish: ["Self-restraint in obedience", "Restraint from sin", "Dignified acceptance of divine destiny"],
      classicalArabicDefinition: "الصَّبْرُ: حَبْسُ النَّفْسِ عَنِ الجَزَعِ، وَحَبْسُ اللِّسَانِ عَنِ الشَّكْوَى، وَحَبْسُ الجَوَارِحِ عَنِ المَعْصِيَةِ",
      hansWehrEquivalent: "ṣabr patience, endurance, perseverance, steadfastness",
    },
    grammar: {
      partOfSpeechArabic: "اسم مفرد (مصدر)",
      partOfSpeechEnglish: "Masculine singular verbal noun (Masdar)",
      grammaticalGender: "masculine",
      number: "singular",
      patterns: "فَعْلٌ (Fa'l)",
      irabAnalysis: [
        {
          word: "صَبْرٌ",
          transliteration: "ṣabr",
          partOfSpeech: "اسم",
          role: "مصدر ثلاثي",
          caseOrState: "معرب (Declinable)",
          explanationEnglish: "Base abstract verbal noun derived from ṣabara.",
        },
      ],
      morphologicalForms: [
        {
          formNumber: "Form I (فَعَلَ)",
          past: "صَبَرَ",
          present: "يَصْبِرُ",
          verbalNoun: "صَبْرٌ",
          activeParticiple: "صَابِرٌ (Patient, persevering)",
          meaning: "To endure, be patient",
        },
        {
          formNumber: "Form III (فَاعَلَ)",
          past: "صَابَرَ",
          present: "يُصَابِرُ",
          verbalNoun: "مُصَابَرَةٌ",
          activeParticiple: "مُصَابِرٌ",
          meaning: "To vie in patience, show endurance against foes",
        },
      ],
    },
    synonyms: [
      { arabic: "جَلَدٌ", english: "Fortitude, endurance" },
      { arabic: "ثَبَاتٌ", english: "Steadfastness, firmness" },
    ],
    antonyms: [
      { arabic: "جَزَعٌ", english: "Impatience, despair" },
      { arabic: "قُنُوطٌ", english: "Despondency" },
    ],
    examples: [
      {
        arabic: "الصَّبْرُ ضِيَاءٌ.",
        english: "Patience is a radiant light. [Sahih Muslim]",
        amharic: "ትዕግስት ብርሃን ናት።",
      },
      {
        arabic: "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
        english: "Indeed, Allah is with the patient. [Al-Baqarah 2:153]",
        amharic: "አላህ ከታጋሾች ጋር ነውና።",
      },
    ],
    quranicInsights: {
      totalOccurrences: 103,
      surahsWithHighFrequency: ["Al-Baqarah", "Ali 'Imran", "Hud", "Yusuf"],
      spiritualLesson:
        "Ibn al-Qayyim categorized Sabr into three pillars: patience in carrying out commands, patience in refraining from prohibitions, and patience with divine decrees.",
      keyVerses: [
        {
          surahNumber: 2,
          ayahNumber: 153,
          surahNameArabic: "البقرة",
          surahNameEnglish: "Al-Baqarah",
          ayahArabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
          ayahTranslation: "O you who have believed, seek help through patience and prayer. Indeed, Allah is with the patient.",
          highlightedWord: "بِالصَّبْرِ",
        },
      ],
    },
    source: "lexicon-db",
    timestamp: Date.now(),
  },
};

export const GRAMMAR_RULES: QamusGrammarRule[] = [
  {
    id: "word-types",
    titleArabic: "أَقْسَامُ الكَلِمَةِ",
    titleEnglish: "The Three Parts of Speech in Arabic",
    category: "nahw",
    summary:
      "Classical Arabic classifies every single vocable into exactly three categories: Ism (Noun/Adjective), Fi'l (Verb), or Harf (Particle).",
    examples: [
      { arabic: "زَيْدٌ كَتَبَ فِي المَسْجِدِ", translation: "Zayd wrote in the mosque", note: "زَيْد (اسم), كَتَبَ (فعل), فِي (حرف)" },
    ],
    chart: [
      { label: "الاِسْمُ (Noun/Name)", formula: "Accepts Tanween (ـٌ), Alif-Lam (الـ), or Kasrah", example: "كِتَابٌ، المَدِينَةُ، صَالِحٌ" },
      { label: "الفِعْلُ (Verb)", formula: "Accepts Qad (قَدْ), Seen (سَـ), Sawfa (سَوْفَ), or Ta Tanith (تْ)", example: "كَتَبَ، يَسْمَعُ، قُلْ" },
      { label: "الحَرْفُ (Particle)", formula: "Has meaning only when connected to a noun or verb", example: "مِنْ، إِلَى، فِي، عَلَى، لَمْ" },
    ],
  },
  {
    id: "verb-forms",
    titleArabic: "الأَوْزَانُ الصَّرْفِيَّةُ العَشَرَةُ",
    titleEnglish: "The 10 Classical Verb Forms (Awzan al-Fi'l)",
    category: "sarf",
    summary:
      "Arabic expands 3-letter roots through augmented morphological templates (Awzan) to convey causation, reciprocity, effort, or reflexivity.",
    examples: [
      { arabic: "عَلِمَ (Form I) ➔ عَلَّمَ (Form II) ➔ تَعَلَّمَ (Form V)", translation: "Knew ➔ Taught ➔ Learned", note: "Augmentation shifts semantic nuance" },
    ],
    chart: [
      { label: "Form I (فَعَلَ / فَعِلَ)", formula: "Base Root Pattern", example: "كَتَبَ (To write)" },
      { label: "Form II (فَعَّلَ)", formula: "Causative / Intensive (Tashdeed on Ayn)", example: "كَتَّبَ (To cause to write), عَلَّمَ (To teach)" },
      { label: "Form III (فَاعَلَ)", formula: "Reciprocity / Interaction (Alif after Fa)", example: "كَاتَبَ (To correspond with), جَاهَدَ (To strive)" },
      { label: "Form IV (أَفْعَلَ)", formula: "Transitive / Causative (Hamza prefix)", example: "أَسْلَمَ (To surrender/submit), أَنْزَلَ (To send down)" },
      { label: "Form V (تَفَعَّلَ)", formula: "Reflexive of Form II (Ta prefix + Tashdeed)", example: "تَعَلَّمَ (To learn), تَكَلَّمَ (To speak)" },
      { label: "Form VI (تَفَاعَلَ)", formula: "Mutual interaction (Ta + Alif)", example: "تَعَاوَنَ (To cooperate), تَبَارَكَ (To be blessed)" },
      { label: "Form VII (اِنْفَعَلَ)", formula: "Passive / Middle voice (In- prefix)", example: "اِنْفَطَرَ (To cleave asunder), اِنْكَسَرَ (To shatter)" },
      { label: "Form VIII (اِفْتَعَلَ)", formula: "Intentional effort (Ifta'ala)", example: "اِكْتَتَبَ (To register), اِجْتَمَعَ (To gather)" },
      { label: "Form IX (اِفْعَلَّ)", formula: "Colors and bodily defects", example: "اِحْمَرَّ (To turn red), اِبْيَضَّ (To turn white)" },
      { label: "Form X (اِسْتَفْعَلَ)", formula: "Seeking or considering (Ista- prefix)", example: "اِسْتَغْفَرَ (To seek forgiveness), اِسْتَعَانَ (To seek aid)" },
    ],
  },
  {
    id: "case-endings",
    titleArabic: "عَلَامَاتُ الإِعْرَابِ",
    titleEnglish: "Arabic Grammatical Cases (I'rab Markers)",
    category: "i'rab",
    summary:
      "Nouns and verbs exhibit grammatical inflection depending on their function in the clause: Raf' (Nominative), Nasb (Accusative), Jarr (Genitive), and Jazm (Jussive).",
    examples: [
      { arabic: "جَاءَ زَيْدٌ (مرفوع) ➔ رَأَيْتُ زَيْدًا (منصوب) ➔ مَرَرْتُ بِزَيْدٍ (مجرور)", translation: "Zayd came ➔ I saw Zayd ➔ I passed by Zayd", note: "Primary vowel markings (Damma, Fatha, Kasra)" },
    ],
    chart: [
      { label: "الرَّفْعُ (Nominative)", formula: "Default for Subject (Fa'il) & Predicate (Khabar)", example: "الضَّمَّةُ (ـُ) or و / ا in Dual & Plural" },
      { label: "النَّصْبُ (Accusative)", formula: "Object (Maf'ul Bihi), Hal, Zarf, Inna's subject", example: "الفَتْحَةُ (ـَ) or ي / ا in Dual & Plural" },
      { label: "الجَرُّ (Genitive)", formula: "After Prepositions (Huruf Jarr) or Mudhaf Ilayh", example: "الكَسْرَةُ (ـِ) or ي in Dual & Plural" },
      { label: "الجَزْمُ (Jussive)", formula: "Only applies to Present Verbs (Mudari') after Lam, In", example: "السُّكُونُ (ـْ) or omission of weak letter" },
    ],
  },
];
